# Обычный Service — через него приложение ходит в базу (DNS: shortlink-db).
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortlink.dbName" . }}
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  selector:
    {{- include "shortlink.selector" . | nindent 4 }}
    app.kubernetes.io/component: db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
# Headless Service — обязателен для StatefulSet (стабильное имя пода shortlink-db-0).
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortlink.dbName" . }}-headless
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  clusterIP: None
  selector:
    {{- include "shortlink.selector" . | nindent 4 }}
    app.kubernetes.io/component: db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
