apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  selector:
    {{- include "shortlink.selector" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: http
